package com.shubham.springbootwebfluxbasic.resources;// Generated by CodiumAI

import com.shubham.springbootwebfluxbasic.servletpattern.dto.Response;
import com.shubham.springbootwebfluxbasic.servletpattern.resources.MathController;
import com.shubham.springbootwebfluxbasic.servletpattern.service.MathService;
import com.shubham.springbootwebfluxbasic.servletpattern.utils.ResponsUtility;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class MathControllerTest {

    @Mock
    private MathService mathService;

    @InjectMocks
    private MathController mathController;

    // can find the square of a positive integer
    @Test
    public void test_find_square_positive_integer() {
        // Mock dependencies

        // Set up test data
        int number = 5;
        ResponseEntity<Response<Integer>> expectedResponse = ResponsUtility.getSuccessResponse(25, "Square of " + number + " is " + 25);

        // Set up mock behavior
        Mockito.when(mathController.findSquare(number)).thenReturn(expectedResponse);

        // Invoke the method under test
        ResponseEntity<Response<Integer>> actualResponse = mathController.findSquare(number);

        // Verify the result
        assertEquals(expectedResponse, actualResponse);
    }

}